routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['namespace' => 'Installer'], function () {
    Route::group(['prefix' => 'install', 'as' => 'Installer::', 'middleware' => ['install']], function () {
        Route::get('/', ['as' => 'welcome', 'uses' => 'HomeController@index']);
        Route::get('environment/classic', ['as' => 'environmentClassic', 'uses' => 'HomeController@index']);
        Route::get('environment/classic', ['as' => 'environmentClassic', 'uses' => 'HomeController@index']);
        //Route::post('environment/saveClassic', ['as' => 'environmentSaveClassic', 'uses' => 'InstallerController@saveClassic']);
        Route::post('environment/saveClassic', ['as' => 'environmentClassic', 'uses' => 'HomeController@index']);
//        Route::get('requirements', ['as' => 'requirements', 'uses' => 'InstallerController@requirements']);
//        Route::get('permissions', ['as' => 'permissions', 'uses' => 'InstallerController@permissions']);
//        Route::get('database', ['as' => 'database', 'uses' => 'InstallerController@database']);
//        Route::get('final', ['as' => 'final', 'uses' => 'InstallerController@finish']);
    });
    Route::group(['prefix' => 'update', 'as' => 'Updater::', 'middleware' => ['update', 'role:admin|developer']], function () {
        Route::get('/', ['as' => 'welcome', 'uses' => 'UpdateController@welcome']);
        Route::get('overview', ['as' => 'overview', 'uses' => 'UpdateController@overview']);
        Route::get('database', ['as' => 'database', 'uses' => 'UpdateController@database']);
    });
});

Auth::routes(['verify' => true]);
// LARAVEL SOCIALITE AUTHENTICATION ROUTES
Route::get('social/redirect/{provider}', ['as' => 'social.redirect', 'uses' => 'Auth\SocialAuthController@redirectToProvider']);
Route::get('social/handle/{provider}', ['as' => 'social.handle', 'uses' => 'Auth\SocialAuthController@handleProviderCallback']);


Route::get('thumbnail/{size}/{filename}', ['as' => 'images.show', 'uses' => 'Frontend\MediasController@imageSizes']);
Route::get('/video-thumbnail/{size}', ['as'=>'images.video', 'uses' => 'Frontend\MediasController@videoImageSizes']);


Route::group(['namespace' => 'Backend', 'middleware' => ['auth', 'verified', 'permission:access-admin']], function () {
    Route::get('dashboard', ['uses' => 'DashboardController@index', 'as' => 'dashboard']);
    Route::get('my-profile', ['as' => 'users.profile', 'uses' => 'UsersController@myProfile']);
    Route::post('my-profile', ['as' => 'users.profile.update', 'uses' => 'UsersController@updateMyProfile']);
    Route::get('my-profile/logs', ['as' => 'users.mylogs', 'uses' => 'UsersController@myLogs']);
    Route::get('my-profile/change-password', ['as' => 'users.profile.change.password', 'uses' => 'UsersController@changePassword']);
    Route::post('my-profile/update-password', ['as' => 'users.profile.update.password', 'uses' => 'UsersController@updateMyPassword']);
});

Route::group(['prefix' => 'admin', 'namespace' => 'Backend', 'middleware' => ['auth', 'verified', 'permission:access-admin']], function () {
    Route::get('/', ['uses' => 'DashboardController@index', 'as' => 'admin']);
    // middleware who can manage users
    Route::group(['middleware' => ['permission:manage-media']], function () {
        Route::get('media/list', ['as' => 'media.lists', 'uses' => 'MediasController@lists']);
        Route::get('media/browse/images', ['as' => 'media.browse', 'uses' => 'MediasController@browseImage']);
        Route::get('media/browse/files', ['as' => 'media.browse.files', 'uses' => 'MediasController@browseFiles']);
        Route::get('media/generate/thumb', ['as' => 'media.thumb.generate', 'uses' => 'MediasController@generateThumbnails']);
        Route::resource('media', 'MediasController');
    });
    // middleware who can manage users
    Route::group(['middleware' => ['permission:manage-users']], function () {
        //users
        Route::resource('users', 'UsersController', ['except' => ['show']]);
        Route::get('users/password/{user_id}', ['uses' => 'UsersController@changePassword', 'as' => 'change.password']);
        Route::put('users/password/{user_id}', ['uses' => 'UsersController@updatePassword', 'as' => 'update.password']);
        Route::get('users/logs/{id}', ['uses' => 'UsersController@userLog', 'as' => 'users.logs']);
        Route::get('users/online', ['uses' => 'UsersController@onlineUsers', 'as' => 'users.online']);
        Route::get('users/suspend/{id}', ['uses' => 'UsersController@suspendUser', 'as' => 'users.suspend']);
        Route::get('users/active/{id}', ['uses' => 'UsersController@activateUser', 'as' => 'users.active']);

    });
    // middleware for developer only
    Route::group(['middleware' => ['role:developer']], function () {
        //roles and permissions
        Route::resource('roles', 'RolesController', ['except' => ['show']]);
        Route::resource('permissions', 'PermissionsController', ['except' => ['show']]);
    });

    // middleware for admin and developer only
    Route::group(['middleware' => ['role:admin|developer']], function () {
        //settings
        Route::resource('adspaces', 'AdspacesController', ['except' => ['show']]);
        Route::get('settings', ['as' => 'settings.index', 'uses' => 'SettingsController@index']);
        Route::post('settings', ['as' => 'settings.store', 'uses' => 'SettingsController@store']);
        Route::resource('messages', 'MessagesController', ['only' => ['index', 'show']]);
        Route::resource('subscribers', 'SubscribersController', ['only' => ['index', 'destroy']]);
        Route::get('subscribers/export/{type}', ['as' => 'subscribers.export', 'uses' => 'SubscribersController@export']);
        Route::get('subscribers/sync', ['as' => 'subscribers.sync', 'uses' => 'SubscribersController@sync']);
    });
    // middleware who can manage posts
    Route::group(['middleware' => ['permission:manage-posts']], function () {
        //posts
        Route::resource('posts', 'PostsController', ['except' => ['show']]);
        Route::get('posts/search', ['as' => 'posts.search.admin', 'uses' => 'PostsController@search']);
        Route::get('posts/draft', ['as' => 'posts.draft', 'uses' => 'PostsController@draft']);
        Route::get('posts/pending', ['as' => 'posts.pending', 'uses' => 'PostsController@pending']);
        Route::get('posts/trash', ['as' => 'posts.trash', 'uses' => 'PostsController@trash']);
        Route::get('posts/trash/empty', ['as' => 'posts.trash.empty', 'uses' => 'PostsController@emptyTrash']);
        Route::get('posts/trash/{id}/restore', ['as' => 'posts.trash.restore', 'uses' => 'PostsController@restoreTrash']);
        Route::delete('posts/trash/{id}/delete', ['as' => 'posts.trash.delete', 'uses' => 'PostsController@deleteTrash']);
        Route::get('posts/check', ['as' => 'posts.check', 'uses' => 'PostsController@checkAllPosts']);
        //categories
        Route::resource('categories', 'CategoriesController', ['except' => ['show']]);
        //tags
        Route::resource('tags', 'TagsController', ['except' => ['show']]);
        Route::get('tags/lists', ['as' => 'tags.lists', 'uses' => 'TagsController@tagslist']);
        Route::resource('comments', 'CommentsController', ['only' => ['index', 'show', 'destroy']]);
        Route::get('comments/suspend/{id}', ['uses' => 'CommentsController@approveComment', 'as' => 'comments.approve']);
        Route::get('comments/active/{id}', ['uses' => 'CommentsController@suspendComment', 'as' => 'comments.suspend']);

    });
    // middleware who can manage menus
    Route::group(['middleware' => ['permission:manage-menus']], function () {
        //menus
        Route::get('menus', ['as' => 'menus.index', 'uses' => 'MenusController@index']);
        Route::get('menus/edit', ['as' => 'menus.edit', 'uses' => 'MenusController@edit']);
        Route::post('menus/store', ['as' => 'menus.store', 'uses' => 'MenusController@store']);
    });
    // middleware who can manage ads
    Route::group(['middleware' => ['permission:manage-ads']], function () {
        //ads controller
        Route::resource('ads', 'AdsController', ['except' => 'show']);
        Route::get('ads/upcoming', ['uses' => 'AdsController@upcoming', 'as' => 'ads.upcoming']);
        Route::get('ads/expired', ['uses' => 'AdsController@expired', 'as' => 'ads.expired']);
    });
    // middleware who can manage pages
    Route::group(['middleware' => ['permission:manage-pages']], function () {
        //pages
        Route::resource('pages', 'PagesController', ['except' => ['show']]);
        Route::post('pages/homepage', ['as' => 'pages.homepage.store', 'uses' => 'PagesController@storeHomepage']);
        Route::get('pages/section', ['as' => 'pages.section', 'uses' => 'PagesController@pageSections']);
    });

    // middleware who can manage widgets
    Route::group(['middleware' => ['permission:manage-widgets']], function () {
        //widgets
        Route::get('widgets', ['as' => 'widgets.index', 'uses' => 'WidgetsController@index']);
        Route::get('widgets/edit', ['as' => 'widgets.edit', 'uses' => 'WidgetsController@edit']);
        Route::post('widgets/store', ['as' => 'widgets.store', 'uses' => 'WidgetsController@store']);
    });
    Route::get('posts/info', ['as' => 'posts.info', 'uses' => 'PostsController@info']);
});

// Frontend Routes


Route::group(['namespace' => 'Frontend', 'middleware' => 'installed'], function () {
    Route::get('/', ['as' => 'home.index', 'uses' => 'HomeController@index']);
    Route::get('/posts/search', ['uses' => 'PostsController@search', 'as' => 'posts.search']);

app/Message.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
    protected $fillable = ['email','full_name','phone','mobile','message'];
}

app/Http/Controllers/Backend/AdsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Adspace;
use App\Http\Requests\Backend\AdRequest;
use App\Http\Controllers\Controller;
use App\Ad;

class AdsController extends Controller
{
    protected $ad;
    protected $adspace;

    public function __construct(Ad $ad, Adspace $adspace){
        $this->ad=$ad;
        $this->adspace=$adspace;
    }

    // Running Ads
    public function index(){
        $advertisements= $this->ad->runningAds()->orderBy('end_date')->paginate(20);
        return view('backend.ads.index',compact('advertisements'));
    }

    // Create Add View
    public function create(){
        $adspaces = $this->adspace->get();
        return view('backend.ads.create', compact('adspaces'));
    }

    //Store function
    public function store(AdRequest $request){
        $advertisement = $this->ad->create($request->all());
        if ($request->has('adspace_id')) {
            $advertisement->adspaces()->sync($request->input('adspace_id'));
        }
        if($request->input('submit') == 'save_continue'){
            return redirect()->route('ads.edit',$advertisement->id);
        }
        return redirect()->route('ads.index')->with('success','Ad Created Successfully');
    }

    //edit page
    public function edit($id){
        $advertisement = $this->ad->findorFail($id);
        $adspaces = $this->adspace->get();
        return view('backend.ads.edit',compact('advertisement','adspaces'));

    }

    //update function
    public function update(AdRequest $request,$id){
        $advertisement = $this->ad->findorFail($id);
        $advertisement->update($request->all());
        if ($request->has('adspace_id')) {
            $advertisement->adspaces()->sync($request->input('adspace_id'));
        }else{
            $advertisement->adspaces()->detach();
        }
        if($request->input('submit') == 'save_continue'){
            return redirect()->route('ads.edit',$advertisement->id);
        }
        return redirect()->route('ads.index')->with('success','Ad Updated Successfully');

    }

    //delte function
    public function destroy($id){
        $advertisement = $this->ad->findorFail($id);
        $advertisement->delete();
        return redirect()->back();
    }

    //upcoming ads
    public function upcoming(){
        $advertisements = $this->ad->upcomingAds()->orderBy('start_date')->paginate();
        return view('backend.ads.upcoming',compact('advertisements'));
    }

    //expired ads
    public function expired(){
        $advertisements=$this->ad->expiredAds()->orderBy('end_date')->paginate();
        return view('backend.ads.expired',compact('advertisements'));
    }
}

app/Http/Controllers/Backend/AdspacesController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Adspace;

class AdSpacesController extends Controller
{
    protected $adspace;

    public function __construct(Adspace $adspace){
        $this->adspace = $adspace;
    }

    //listing all adspaces
    public function index(){
        $adspaces=$this->adspace->orderBy('created_at')->paginate(20);
        return view('backend.adspaces.index',compact('adspaces'));
    }

    //storing adspaces
    public function store(Request $request){
        $this->validate($request,[
            'name' => 'required|string|max:255',
        ]);
        try{
            $this->adspace->create($request->only('slug', 'name', 'description'));
        }catch (\Exception $exception){
            dd($exception);
        }
        return redirect()->route('adspaces.index')->with('success','Ad Space Successfully updated!');
    }

    //delete fcuntion for adspaces
    public function destroy($id){
        try{
            $adspace=$this->adspace->findorFail($id);
            $adspace->delete();
        }catch (\Exception $exception){
            dd($exception);
        }
        return redirect()->back()->with('success','Ad Space Successfully Deleted!');
    }
    //edit page for adspaces
    public function edit($id){
        $adspace=$this->adspace->findOrFail($id);
        return view('backend.adspaces.edit',compact('adspace'));
    }

    //updating adspaces
    public function update(Request $request,$id){
        $this->validate($request,[
            'name' => 'required|string|max:255',
        ]);
        try{
            $adspace = $this->adspace->findOrFail($id);
            $adspace->update($request->only('name', 'description'));
        }catch (\Exception $exception){
            dd($exception);
        }
        return redirect()->route('adspaces.index')->with('success','Ad Space Successfully updated!');
    } 
}

app/Http/Controllers/Backend/CategoriesController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Str;
use App\Category;

class CategoriesController extends Controller
{
    protected $category;

    public function __construct(Category $category){
        $this->category = $category;
    }

    public function index(){
        $categories = $this->category->whereNull('parent_id')->with('children')->paginate();
        $allCategories = $this->category->pluck('name','id')->all();
    	return view('backend.categories.index',compact('categories','allCategories'));
    }

    //storing the newly created category
    public function store(Request $request){
    	$this->validate($request,[
    		'name'=>'required',
            'slug'=>'required|unique:categories'
        ]);
    	$input = $request->all();
        $input['parent_id'] = empty($input['parent_id']) ? NULL : $input['parent_id'];
        $this->category->create($input);
        return redirect()->back()->with('success','Category added successfully!');
    }

    
    //delete funtion
    public function destroy($id){
    	$category=$this->category->findorFail($id);
    	$category->delete();
    	return redirect()->back()->with('success','Category deleted successfully!');
    }

    public function edit($id){
    	$category=$this->category->find($id);
        $allCategories = $this->category->whereNull('parent_id')->where('id', '<>', $category->id)->pluck('name','id')->all();
        return view('backend.categories.edit',compact('category','allCategories'));
    }

    public function update(Request $request,$id){
    	$this->validate($request,[
    		'name'=>'required',
            'slug'=>'required'
    		]);
 		$category=$this->category->find($id);
        $parent_id = empty($request->input('parent_id')) ? NULL : $request->input('parent_id');
 		$category->update([
 			'name'=>$request->name,
 			'description'=>$request->description,
            'slug'=>$request->slug,
            'parent_id'=>$parent_id,
        ]);
 		return redirect()->route('categories.index')->with('success','Category updated successfully!');
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Category;
use App\Post;
use App\User;

class DashboardController extends Controller
{

    public function __construct(Category $category, Post $post, User $user){
    	$this->category=$category;
    	$this->post=$post;
    	$this->user=$user;
    }

    public function index(){
        $recentPosts= $this->post->published()->latest('publish_on')->take(5)->get();
        $popularPosts= $this->post->published()->orderBy('view_count', 'DESC')->take(5)->get();
        $users = $this->user->latest('created_at')->take(5)->get();
        return view('backend.dashboard', compact('recentPosts','popularPosts', 'users'));
    }
}

resources/views/backend/messages/index.blade.php
@extends('backend.layout')
@section('title') {{ __('site.message.messages')  }} @endsection
@section('content')
    <div class="page-subheader mb-3">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-md-12">
                    <div class="list">
                        <i class="fa fa-file-text-o rounded-circle fs20 text-muted text-primary d-inline-block v-m"></i>
                        <span class="d-inline-block title-lg ml-3 v-m"> {{ __('site.message.messages')  }} - {{ __('site.message.all_messages') }}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="page-content d-flex flex flex-column mb-30">
        <div class=" table-responsive-sm">
            <table class="table table-sm">
                <thead>
                <tr class="uppercase">
                    <th class="text-center">#</th>
                    <th>{{ __('site.full_name')  }}</th>
                    <th>{{ __('site.email')  }}</th>
                    <th>{{ __('site.message.messaged_at')  }}</th>
                    <th class="text-center">{{ __('site.actions')  }}</th>
                </tr>
                </thead>
                <tbody>
                @foreach($messages as $message)
                    <tr>
                        <td class="text-center">#</td>
                        <td>{{$message->full_name}}</td>
                        <td>{{$message->email}}</td>
                        <td>{{$message->created_at->format('l, d M Y')}}</td>
                        <td class="text-center">
                            <div class="btn-group">
                                <a href="{{route('messages.show',$message->id)}}" class="btn btn-sm btn-light"
                                   data-toggle="tooltip" title="" data-original-title="{{ __('site.message.show_message')  }}"><i
                                        class="fa fa-eye" aria-hidden="true"></i></a>
                            </div>
                        </td>
                @endforeach

                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/backend/messages/show.blade.php
@extends('backend.layout')
@section('title') {{ __('site.message.messages') }} @endsection
@section('content')
    <div class="page-subheader mb-3">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-md-7">
                    <div class="list">
                        <i class="fa fa-file-text-o rounded-circle fs20 text-muted text-primary d-inline-block v-m"></i>
                        <span class="d-inline-block title-lg ml-3 v-m">  {{ __('site.message.messages') }} -  {{ __('site.message.message_detail') }}</span>
                    </div>
                </div>
                <div class="col-md-5">
                  <div class="pull-right">
                      <a class="btn btn-outline-dark btn-sm" href="{{ url()->previous() }}">
                          <i class="fa fa-angle-left"></i> {{ __('site.message.back_to_messages_list') }}
                      </a>
                  </div>
                </div>
            </div>
        </div>
    </div>
    <div class="page-content d-flex flex flex-column mb-30">
        <div class="table-responsive">
            <table class="table table-borderless text-left mb-0">
                <thead>
                <th style="width: 250px;"></th>
                <th style="width: 50px;"></th>
                <th></th>
                </thead>
                <tbody>
                <tr>
                    <td>{{ __('site.message.messaged_at') }}</td>
                    <td>:</td>
                    <td><mark class="text-black">{{ $message->created_at->format('l, d M Y') }}</mark></td>
                </tr>
                <tr>
                    <td>{{ __('site.full_name')  }}</td>
                    <td>:</td>
                    <td>{{ $message->full_name }}</td>
                </tr>
                <tr>
                    <td>{{ __('site.email')  }}</td>
                    <td>:</td>
                    <td>
                        <a class="text-primary" href="mailto:{{ $message->email }}">
                            {{ $message->email }}
                        </a>
                    </td>
                </tr>
                <tr>
                    <td class="font-w600">{{ __('site.phone')  }}</td>
                    <td>:</td>
                    <td>
                        <a class="text-primary" href="tel:{{ $message->phone }}">
                            {{ $message->phone }}
                        </a>
                    </td>
                </tr>
                <tr>
                    <td class="font-w600">{{ __('site.mobile')  }}</td>
                    <td>:</td>
                    <td>
                        <a class="text-primary" href="tel:{{ $message->mobile }}">
                            {{ $message->mobile }}
                        </a>
                    </td>
                </tr>
                <tr>
                    <td class="font-w600">{{ __('site.message.message')  }}</td>
                    <td>:</td>
                    <td>{{ $message->message }}</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
@endsection