routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['namespace' => 'Installer'], function () {
    Route::group(['prefix' => 'install', 'as' => 'Installer::', 'middleware' => ['install']], function () {
        Route::get('/', ['as' => 'welcome', 'uses' => 'HomeController@index']);
        Route::get('environment/classic', ['as' => 'environmentClassic', 'uses' => 'HomeController@index']);
        Route::get('environment/classic', ['as' => 'environmentClassic', 'uses' => 'HomeController@index']);
        //Route::post('environment/saveClassic', ['as' => 'environmentSaveClassic', 'uses' => 'InstallerController@saveClassic']);
        Route::post('environment/saveClassic', ['as' => 'environmentClassic', 'uses' => 'HomeController@index']);
//        Route::get('requirements', ['as' => 'requirements', 'uses' => 'InstallerController@requirements']);
//        Route::get('permissions', ['as' => 'permissions', 'uses' => 'InstallerController@permissions']);
//        Route::get('database', ['as' => 'database', 'uses' => 'InstallerController@database']);
//        Route::get('final', ['as' => 'final', 'uses' => 'InstallerController@finish']);
    });
    Route::group(['prefix' => 'update', 'as' => 'Updater::', 'middleware' => ['update', 'role:admin|developer']], function () {
        Route::get('/', ['as' => 'welcome', 'uses' => 'UpdateController@welcome']);
        Route::get('overview', ['as' => 'overview', 'uses' => 'UpdateController@overview']);
        Route::get('database', ['as' => 'database', 'uses' => 'UpdateController@database']);
    });
});

Auth::routes(['verify' => true]);
// LARAVEL SOCIALITE AUTHENTICATION ROUTES
Route::get('social/redirect/{provider}', ['as' => 'social.redirect', 'uses' => 'Auth\SocialAuthController@redirectToProvider']);
Route::get('social/handle/{provider}', ['as' => 'social.handle', 'uses' => 'Auth\SocialAuthController@handleProviderCallback']);


Route::get('thumbnail/{size}/{filename}', ['as' => 'images.show', 'uses' => 'Frontend\MediasController@imageSizes']);
Route::get('/video-thumbnail/{size}', ['as'=>'images.video', 'uses' => 'Frontend\MediasController@videoImageSizes']);


Route::group(['namespace' => 'Backend', 'middleware' => ['auth', 'verified', 'permission:access-admin']], function () {
    Route::get('dashboard', ['uses' => 'DashboardController@index', 'as' => 'dashboard']);
    Route::get('my-profile', ['as' => 'users.profile', 'uses' => 'UsersController@myProfile']);
    Route::post('my-profile', ['as' => 'users.profile.update', 'uses' => 'UsersController@updateMyProfile']);
    Route::get('my-profile/logs', ['as' => 'users.mylogs', 'uses' => 'UsersController@myLogs']);
    Route::get('my-profile/change-password', ['as' => 'users.profile.change.password', 'uses' => 'UsersController@changePassword']);
    Route::post('my-profile/update-password', ['as' => 'users.profile.update.password', 'uses' => 'UsersController@updateMyPassword']);
});

Route::group(['prefix' => 'admin', 'namespace' => 'Backend', 'middleware' => ['auth', 'verified', 'permission:access-admin']], function () {
    Route::get('/', ['uses' => 'DashboardController@index', 'as' => 'admin']);
    // middleware who can manage users
    Route::group(['middleware' => ['permission:manage-media']], function () {
        Route::get('media/list', ['as' => 'media.lists', 'uses' => 'MediasController@lists']);
        Route::get('media/browse/images', ['as' => 'media.browse', 'uses' => 'MediasController@browseImage']);
        Route::get('media/browse/files', ['as' => 'media.browse.files', 'uses' => 'MediasController@browseFiles']);
        Route::get('media/generate/thumb', ['as' => 'media.thumb.generate', 'uses' => 'MediasController@generateThumbnails']);
        Route::resource('media', 'MediasController');
    });
    // middleware who can manage users
    Route::group(['middleware' => ['permission:manage-users']], function () {
        //users
        Route::resource('users', 'UsersController', ['except' => ['show']]);
        Route::get('users/password/{user_id}', ['uses' => 'UsersController@changePassword', 'as' => 'change.password']);
        Route::put('users/password/{user_id}', ['uses' => 'UsersController@updatePassword', 'as' => 'update.password']);
        Route::get('users/logs/{id}', ['uses' => 'UsersController@userLog', 'as' => 'users.logs']);
        Route::get('users/online', ['uses' => 'UsersController@onlineUsers', 'as' => 'users.online']);
        Route::get('users/suspend/{id}', ['uses' => 'UsersController@suspendUser', 'as' => 'users.suspend']);
        Route::get('users/active/{id}', ['uses' => 'UsersController@activateUser', 'as' => 'users.active']);

    });
    // middleware for developer only
    Route::group(['middleware' => ['role:developer']], function () {
        //roles and permissions
        Route::resource('roles', 'RolesController', ['except' => ['show']]);
        Route::resource('permissions', 'PermissionsController', ['except' => ['show']]);
    });

    // middleware for admin and developer only
    Route::group(['middleware' => ['role:admin|developer']], function () {
        //settings
        Route::resource('adspaces', 'AdspacesController', ['except' => ['show']]);
        Route::get('settings', ['as' => 'settings.index', 'uses' => 'SettingsController@index']);
        Route::post('settings', ['as' => 'settings.store', 'uses' => 'SettingsController@store']);
        Route::resource('messages', 'MessagesController', ['only' => ['index', 'show']]);
        Route::resource('subscribers', 'SubscribersController', ['only' => ['index', 'destroy']]);
        Route::get('subscribers/export/{type}', ['as' => 'subscribers.export', 'uses' => 'SubscribersController@export']);
        Route::get('subscribers/sync', ['as' => 'subscribers.sync', 'uses' => 'SubscribersController@sync']);
    });
    // middleware who can manage posts
    Route::group(['middleware' => ['permission:manage-posts']], function () {
        //posts
        Route::resource('posts', 'PostsController', ['except' => ['show']]);
        Route::get('posts/search', ['as' => 'posts.search.admin', 'uses' => 'PostsController@search']);
        Route::get('posts/draft', ['as' => 'posts.draft', 'uses' => 'PostsController@draft']);
        Route::get('posts/pending', ['as' => 'posts.pending', 'uses' => 'PostsController@pending']);
        Route::get('posts/trash', ['as' => 'posts.trash', 'uses' => 'PostsController@trash']);
        Route::get('posts/trash/empty', ['as' => 'posts.trash.empty', 'uses' => 'PostsController@emptyTrash']);
        Route::get('posts/trash/{id}/restore', ['as' => 'posts.trash.restore', 'uses' => 'PostsController@restoreTrash']);
        Route::delete('posts/trash/{id}/delete', ['as' => 'posts.trash.delete', 'uses' => 'PostsController@deleteTrash']);
        Route::get('posts/check', ['as' => 'posts.check', 'uses' => 'PostsController@checkAllPosts']);
        //categories
        Route::resource('categories', 'CategoriesController', ['except' => ['show']]);
        //tags
        Route::resource('tags', 'TagsController', ['except' => ['show']]);
        Route::get('tags/lists', ['as' => 'tags.lists', 'uses' => 'TagsController@tagslist']);
        Route::resource('comments', 'CommentsController', ['only' => ['index', 'show', 'destroy']]);
        Route::get('comments/suspend/{id}', ['uses' => 'CommentsController@approveComment', 'as' => 'comments.approve']);
        Route::get('comments/active/{id}', ['uses' => 'CommentsController@suspendComment', 'as' => 'comments.suspend']);

    });
    // middleware who can manage menus
    Route::group(['middleware' => ['permission:manage-menus']], function () {
        //menus
        Route::get('menus', ['as' => 'menus.index', 'uses' => 'MenusController@index']);
        Route::get('menus/edit', ['as' => 'menus.edit', 'uses' => 'MenusController@edit']);
        Route::post('menus/store', ['as' => 'menus.store', 'uses' => 'MenusController@store']);
    });
    // middleware who can manage ads
    Route::group(['middleware' => ['permission:manage-ads']], function () {
        //ads controller
        Route::resource('ads', 'AdsController', ['except' => 'show']);
        Route::get('ads/upcoming', ['uses' => 'AdsController@upcoming', 'as' => 'ads.upcoming']);
        Route::get('ads/expired', ['uses' => 'AdsController@expired', 'as' => 'ads.expired']);
    });
    // middleware who can manage pages
    Route::group(['middleware' => ['permission:manage-pages']], function () {
        //pages
        Route::resource('pages', 'PagesController', ['except' => ['show']]);
        Route::post('pages/homepage', ['as' => 'pages.homepage.store', 'uses' => 'PagesController@storeHomepage']);
        Route::get('pages/section', ['as' => 'pages.section', 'uses' => 'PagesController@pageSections']);
    });

    // middleware who can manage widgets
    Route::group(['middleware' => ['permission:manage-widgets']], function () {
        //widgets
        Route::get('widgets', ['as' => 'widgets.index', 'uses' => 'WidgetsController@index']);
        Route::get('widgets/edit', ['as' => 'widgets.edit', 'uses' => 'WidgetsController@edit']);
        Route::post('widgets/store', ['as' => 'widgets.store', 'uses' => 'WidgetsController@store']);
    });
    Route::get('posts/info', ['as' => 'posts.info', 'uses' => 'PostsController@info']);
});

// Frontend Routes


Route::group(['namespace' => 'Frontend', 'middleware' => 'installed'], function () {
    Route::get('/', ['as' => 'home.index', 'uses' => 'HomeController@index']);
    Route::get('/posts/search', ['uses' => 'PostsController@search', 'as' => 'posts.search']);

resources/views/themes/kMag/partials/ads.blade.php
@foreach($adspaces as $adspace)
    @if($adspace->ads)
    @push($adspace->ad_position)
        @php $ad = $adspace->ads(function ($q){
            $q->runningAds();
        })->first(); @endphp
        <div class="adv-holder spacer">
            @if($ad->ad_type == 'image_ad')
                <div class="text-center">
                    <a href="{{ $ad->url }}" target="_blank">
                        <img src="{{ url($ad->media->media_url) }}" class="img-responsive" alt="{{ $ad->title }}"/>
                    </a>
                </div>
            @else
                {!! $ad->script !!}
            @endif
        </div>
    @endpush
    @endif
@endforeach

resources/views/themes/kMag/partials/head-meta.blade.php
    <meta name="robots" content="all">
    <meta name="description" content="{{ !empty($description)? $description : '' }}">
    <meta name="keywords" content="{{ !empty($keywords)? $keywords : '' }}">

    <!-- Facebook OpenGraph -->
    <meta property="og:locale" content="{{  config('app.locale') }}">
    <meta property="og:type" content="article">
    <meta property="og:url" content="{{ url()->current() }}">
    <meta property="og:title" content="{{ !empty($title)? $title : '' }}">
    <meta property="og:description" content="{{ !empty($description)? $description : '' }}">
    <meta property="og:image" content="{{ !empty($image)? $image : setting('site_logo') }}">
    <meta property="og:site_name" content="{{  config('app.name') }}">

    <meta name="twitter:title" content="{{ !empty($title)? $title : '' }}">
    <meta name="twitter:description" content="{{ !empty($description)? $description : '' }}">
    <meta name="twitter:image" content="{{ !empty($image)? $image : setting('site_logo') }}">
    <!-- Google Plus Full-Bleed Image -->
    <meta itemprop="og:headline" content="{{ !empty($image)? $image : setting('site_logo') }}" />

resources/views/themes/kMag/partials/message-form.blade.php
<div class="message-box">
    @if(count($errors)>0)
        <div class="alert-icon alert alert-danger alert-dismissible" role="alert">
            Something went wrong. Please check below
        </div>
    @endif
    @if(session('success'))
        <div class="alert-icon alert alert-success alert-dismissible" role="alert">
            {{ session('success') }}
        </div>
    @endif
    {!! Form::open(array('route' => ['messages.create'], 'method' => 'POST', 'role' => 'form')) !!}
    <div class="form-group  {{$errors->has('full_name') ? 'is-invalid':''}}">
        {!! Form::text('full_name',\Auth::user()?auth()->user()->profile->full_name:old('full_name'),['class'=>'form-control','placeholder'=>'your full name','required']) !!}
        @if ($errors->has('full_name'))
            <span class="text-danger">
                    {{ $errors->first('full_name') }}
                </span>
        @endif
    </div>
    <div class="form-group {{$errors->has('email') ? 'is-invalid':''}}">
        {!! Form::email('email',\Auth::user()?auth()->user()->email:old('email'),['class'=>'form-control','placeholder'=>'your email','required']) !!}
        @if ($errors->has('email'))
            <span class="text-danger">
                    {{ $errors->first('email') }}
                </span>
        @endif
    </div>
    <div class="form-group {{$errors->has('phone') ? 'is-invalid':''}}">
        {!! Form::text('phone',old('phone'),['class'=>'form-control','placeholder'=>'your phone number']) !!}
        @if ($errors->has('phone'))
            <span class="text-danger">
                    {{ $errors->first('phone') }}
                </span>
        @endif
    </div>
    <div class="form-group {{$errors->has('mobile') ? 'is-invalid':''}}">
        {!! Form::email('mobile',old('mobile'),['class'=>'form-control','placeholder'=>'your mobile number']) !!}
        @if ($errors->has('mobile'))
            <span class="text-danger">
                    {{ $errors->first('mobile') }}
                </span>
        @endif
    </div>
    <div class="form-group {{$errors->has('message') ? 'is-invalid':''}}">
        {!! Form::textarea('message',old('message'),['class'=>'form-control','placeholder'=>'your message','required']) !!}
        @if ($errors->has('message'))
            <span class="text-danger">
                    {{ $errors->first('message') }}
                </span>
        @endif
    </div>
    <button type="submit" class="btn primary-btn">Send Message</button>
    {!! Form::close() !!}
</div>

resources/views/themes/kMag/partials/module-breaking-news-l2.blade.php
    <section class="billboard-news-module style-2">
        <div class="container">
        @php $k = 0; @endphp
        @foreach($posts as $post)
            @if($k==0)
                <article class="post overlay-post full row no-gutters"
                         style="background: url({{ $post->media?route('images.show', ['large',$post->media->filename]):$post->video_image }}) no-repeat center center / cover ;">

                    <a class="col-md-7 col-lg-8" href="{{ route('posts.show', $post->slug) }}">
                        <div class="post-media row justify-content-center no-gutters">
                            <div class="col-md-10">
                                @if($post->format == 'video')
                                    <span class="media-item"><i class="icon-play"></i></span>
                                @endif
                            </div>
                        </div>
                    </a>
                    <div class="post-entry col-md-7 col-lg-8">
                        <div class="row justify-content-center no-gutters">
                            <div class="col-11 col-md-10">
                                @if($post->categories)
                                    <div class="post-cat">
                                        @foreach($post->categories as $cat)
                                            <a href="{{ route('categories.show', $cat->slug) }}">{{ $cat->name }}</a>
                                        @endforeach
                                    </div>
                                @endif
                                <h2 class="post-title">
                                    <a href="{{ route('posts.show', $post->slug) }}">{{ $post->title }}</a>
                                </h2>
                                 {{ post_meta($post) }}
                            </div>
                        </div>
                    </div>
                </article>
            @endif
            @if($k==1)
                <div class="row justify-content-end no-gutters">
                    <div class="col-md-5 col-lg-4 news-list">
                        @endif
                        @if($k!=0)
                            <article class="post list-post">
                                <div class="post-entry">
                                    <h2 class="post-title"><a
                                                href="{{ route('posts.show', $post->slug) }}">{{ $post->title }}</a>
                                    </h2>
                                    {{ post_meta($post) }}
                                </div>
                            </article>
                        @endif
                        @if($k==5)
                    </div>
                </div>
            @endif
            @php $k++; @endphp
        @endforeach
        </div>
    </section>

resources/views/themes/kMag/partials/module-breaking-news.blade.php
<section class="billboard-news-module">
    <div class="container">
        <div class="row">
            @php $k = 0; @endphp
            @foreach($posts as $post)
                @if($k == 0 || $k == 1)
                    <div class="col-md-6">
                        @endif
                        @if($k == 1)
                            <div class="row">
                                <div class="col-md-12">
                                    @endif
                                    @if($k == 2 || $k == 3)
                                        <div class="col-md-6 col-sm-6">
                                            @endif
                                            @if($k <4)
                                            <article class="post overlay-post @if($k ==0)large @elseif($k == 1)medium @endif">
                                                <a href="{{ route('posts.show', $post->slug) }}">
                                                    <div class="post-media"
                                                         style="background: url({{ $post->media?route('images.show', ['large',$post->media->filename]):$post->video_image }}) no-repeat center center / cover ;">
                                                        @if($post->format == 'video')
                                                            <span class="media-item"><i class="icon-play"></i></span>
                                                        @endif
                                                    </div>
                                                </a>
                                                <div class="post-entry">
                                                    @if($post->categories)
                                                        <div class="post-cat">
                                                            @foreach($post->categories as $cat)
                                                                <a href="{{ route('categories.show', $cat->slug) }}">{{ $cat->name }}</a>
                                                            @endforeach
                                                        </div>
                                                    @endif
                                                    <h2 class="post-title">
                                                        <a href="{{ route('posts.show', $post->slug) }}">{{ $post->title }}</a>
                                                    </h2>
                                                        {{  post_meta($post) }}
                                                </div>
                                            </article>
                                            @endif
                                            @if($k == 0 || $k == 3)
                                        </div>
                                    @endif
                                    @if($k == 1)
                                </div>
                                @endif
                                @if($k == 2 || $k == 3)
                            </div>
                        @endif
                        @if($k == 3)
                    </div>
                @endif
                @php $k++; @endphp
            @endforeach
        </div>
    </div>
    </div>
</section>

resources/views/themes/kMag/partials/module-cat-billboard.blade.php
@if(count($posts) > 3)
<section class="billboard-news-module billboard-cat-news-module module module--billboard-cat style-2">
    <div class="container">
        @php $k = 0; @endphp
        @foreach($posts as $post)
            @if($k==0)
                <article class="post overlay-post full row no-gutters"
                         style="background: url({{ $post->media?url($post->media->media_url):$post->video_image }}) no-repeat center center / cover ;">
                    <a class="col-md-7 col-lg-8" href="{{ route('posts.show', $post->slug) }}">
                        <div class="post-media row justify-content-center no-gutters">
                            <div class="col-md-10">
                                @if($post->format == 'video')
                                    <span class="media-item"><i class="icon-play"></i></span>
                                @endif
                            </div>
                        </div>
                    </a>
                    <div class="post-entry col-md-7 col-lg-8">
                        <div class="row justify-content-center no-gutters">
                            <div class="col-11 col-md-10">
                                @if($post->categories)
                                    <div class="post-cat">
                                        @foreach($post->categories as $cat)
                                            <a href="{{ route('categories.show', $cat->slug) }}">{{ $cat->name }}</a>
                                        @endforeach
                                    </div>
                                @endif
                                <h2 class="post-title">
                                    <a href="{{ route('posts.show', $post->slug) }}">{{ $post->title }}</a>
                                </h2>
                                    {{ post_meta($post) }}
                            </div>
                        </div>
                    </div>
                </article>
            @endif
            @if($k==1)
                <div class="row justify-content-end no-gutters">
                    <div class="col-md-5 col-lg-4 news-list">
                        <div class="row align-items-center module__header">
                            <h2 class="module__title mb-0 col-auto">Top {{ isset($name)?$name:'' }} Stories</h2>
                            <div class="col pl-0">
                                <div class="line"></div>
                            </div>
                        </div>
                        @endif
                        @if($k!=0)
                            <article class="post list-post">
                                <div class="post-entry">
                                    <h2 class="post-title"><a
                                                href="{{ route('posts.show', $post->slug) }}">{{ $post->title }}</a>
                                    </h2>
                                    {{ post_meta($post) }}
                                </div>
                            </article>
                        @endif
                        @if($k==5)
                    </div>
                </div>
            @endif
            @php $k++; @endphp
        @endforeach
    </div>
</section>
@endif

resources/views/themes/kMag/partials/module-cover-news.blade.php
<section class="top-stories-module">
    <div class="container">
        <div class="row">
            @foreach($posts as $post)
                <article class="col-6 col-md-4 col-lg post-wrap">
                    <div class="post">
                        <h2 class="post-title"><a href="{{ route('posts.show', $post->slug) }}">{{ $post->title }}</a></h2>
                    </div>
                </article>
            @endforeach
        </div>
    </div>
</section>

resources/views/themes/kMag/partials/module-missed-posts.blade.php
<section class="related-news news-column">
    <div class="container">
        <h2 class="sec-heading row align-items-center"><span
                    class="col-auto">{{ setting('missed_post_title') }}</span><span class="col pl-0"><span
                        class="d-block divider"></span></span></h2>
        <div class="row">
            @for($i=0;$i<2;$i++)
                @foreach($missed_news as $post)
                    <div class="col-md-4">
                        <article class="post post--category grid-post grid-post--medium">
                            {{ featured_image($post, 'small', null, true) }}
                            <div class="post-entry">
                                <h2 class="post-title"><a href="{{ route('posts.show', $post->slug) }}">{{ $post->title }}</a></h2>
                                {{ post_meta($post) }}
                            </div>
                        </article>
                    </div>
                @endforeach
            @endfor
        </div>
    </div>
</section>

resources/views/themes/kMag/partials/module-search-box.blade.php
<div class="search-overlay overlay-module">
    <div class="nav-close close-trigger">
            <span class="burger">
            </span>
    </div>
    <div class="overlay-main">
        <div class="overlay-entry  d-flex justify-content-center flex-column">
            {!! Form::open(array('route' => 'posts.search',  'method' => 'GET', 'class' => 'search-form')) !!}
                {!! Form::text('s',old('s'), array('class' => 'search-field', 'placeholder' => 'Search...', 'required'=>'required')) !!}
                <div class="submit">
                    <input type="submit" class="search-submit" value="Search..."><i class="fa fa-search"></i>
                </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>

resources/views/themes/kMag/partials/module-widget-related.blade.php
<section class="news-module related-module">
    <div class="news-sec-heading">
      <div class="tag"><a href="javascript:void(0);">Related</a></div>
    </div>
    <div class="row">
      @foreach($posts as $post)
            <div class="col-md-6">
                <article class="post post--category grid-post grid-post--medium">
                    {{ featured_image($post, 'medium', null, true) }}
                    <div class="post-entry">
                        <h2 class="post-title"><a
                                    href="{{ route('posts.show', $post->slug) }}">{{ $post->title }}</a>
                        </h2>
                        {{ post_meta($post) }}
                    </div>
                </article>
            </div>
      @endforeach
    </div>
</section>