routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['namespace' => 'Installer'], function () {
    Route::group(['prefix' => 'install', 'as' => 'Installer::', 'middleware' => ['install']], function () {
        Route::get('/', ['as' => 'welcome', 'uses' => 'HomeController@index']);
        Route::get('environment/classic', ['as' => 'environmentClassic', 'uses' => 'HomeController@index']);
        Route::get('environment/classic', ['as' => 'environmentClassic', 'uses' => 'HomeController@index']);
        //Route::post('environment/saveClassic', ['as' => 'environmentSaveClassic', 'uses' => 'InstallerController@saveClassic']);
        Route::post('environment/saveClassic', ['as' => 'environmentClassic', 'uses' => 'HomeController@index']);
//        Route::get('requirements', ['as' => 'requirements', 'uses' => 'InstallerController@requirements']);
//        Route::get('permissions', ['as' => 'permissions', 'uses' => 'InstallerController@permissions']);
//        Route::get('database', ['as' => 'database', 'uses' => 'InstallerController@database']);
//        Route::get('final', ['as' => 'final', 'uses' => 'InstallerController@finish']);
    });
    Route::group(['prefix' => 'update', 'as' => 'Updater::', 'middleware' => ['update', 'role:admin|developer']], function () {
        Route::get('/', ['as' => 'welcome', 'uses' => 'UpdateController@welcome']);
        Route::get('overview', ['as' => 'overview', 'uses' => 'UpdateController@overview']);
        Route::get('database', ['as' => 'database', 'uses' => 'UpdateController@database']);
    });
});

Auth::routes(['verify' => true]);
// LARAVEL SOCIALITE AUTHENTICATION ROUTES
Route::get('social/redirect/{provider}', ['as' => 'social.redirect', 'uses' => 'Auth\SocialAuthController@redirectToProvider']);
Route::get('social/handle/{provider}', ['as' => 'social.handle', 'uses' => 'Auth\SocialAuthController@handleProviderCallback']);


Route::get('thumbnail/{size}/{filename}', ['as' => 'images.show', 'uses' => 'Frontend\MediasController@imageSizes']);
Route::get('/video-thumbnail/{size}', ['as'=>'images.video', 'uses' => 'Frontend\MediasController@videoImageSizes']);


Route::group(['namespace' => 'Backend', 'middleware' => ['auth', 'verified', 'permission:access-admin']], function () {
    Route::get('dashboard', ['uses' => 'DashboardController@index', 'as' => 'dashboard']);
    Route::get('my-profile', ['as' => 'users.profile', 'uses' => 'UsersController@myProfile']);
    Route::post('my-profile', ['as' => 'users.profile.update', 'uses' => 'UsersController@updateMyProfile']);
    Route::get('my-profile/logs', ['as' => 'users.mylogs', 'uses' => 'UsersController@myLogs']);
    Route::get('my-profile/change-password', ['as' => 'users.profile.change.password', 'uses' => 'UsersController@changePassword']);
    Route::post('my-profile/update-password', ['as' => 'users.profile.update.password', 'uses' => 'UsersController@updateMyPassword']);
});

Route::group(['prefix' => 'admin', 'namespace' => 'Backend', 'middleware' => ['auth', 'verified', 'permission:access-admin']], function () {
    Route::get('/', ['uses' => 'DashboardController@index', 'as' => 'admin']);
    // middleware who can manage users
    Route::group(['middleware' => ['permission:manage-media']], function () {
        Route::get('media/list', ['as' => 'media.lists', 'uses' => 'MediasController@lists']);
        Route::get('media/browse/images', ['as' => 'media.browse', 'uses' => 'MediasController@browseImage']);
        Route::get('media/browse/files', ['as' => 'media.browse.files', 'uses' => 'MediasController@browseFiles']);
        Route::get('media/generate/thumb', ['as' => 'media.thumb.generate', 'uses' => 'MediasController@generateThumbnails']);
        Route::resource('media', 'MediasController');
    });
    // middleware who can manage users
    Route::group(['middleware' => ['permission:manage-users']], function () {
        //users
        Route::resource('users', 'UsersController', ['except' => ['show']]);
        Route::get('users/password/{user_id}', ['uses' => 'UsersController@changePassword', 'as' => 'change.password']);
        Route::put('users/password/{user_id}', ['uses' => 'UsersController@updatePassword', 'as' => 'update.password']);
        Route::get('users/logs/{id}', ['uses' => 'UsersController@userLog', 'as' => 'users.logs']);
        Route::get('users/online', ['uses' => 'UsersController@onlineUsers', 'as' => 'users.online']);
        Route::get('users/suspend/{id}', ['uses' => 'UsersController@suspendUser', 'as' => 'users.suspend']);
        Route::get('users/active/{id}', ['uses' => 'UsersController@activateUser', 'as' => 'users.active']);

    });
    // middleware for developer only
    Route::group(['middleware' => ['role:developer']], function () {
        //roles and permissions
        Route::resource('roles', 'RolesController', ['except' => ['show']]);
        Route::resource('permissions', 'PermissionsController', ['except' => ['show']]);
    });

    // middleware for admin and developer only
    Route::group(['middleware' => ['role:admin|developer']], function () {
        //settings
        Route::resource('adspaces', 'AdspacesController', ['except' => ['show']]);
        Route::get('settings', ['as' => 'settings.index', 'uses' => 'SettingsController@index']);
        Route::post('settings', ['as' => 'settings.store', 'uses' => 'SettingsController@store']);
        Route::resource('messages', 'MessagesController', ['only' => ['index', 'show']]);
        Route::resource('subscribers', 'SubscribersController', ['only' => ['index', 'destroy']]);
        Route::get('subscribers/export/{type}', ['as' => 'subscribers.export', 'uses' => 'SubscribersController@export']);
        Route::get('subscribers/sync', ['as' => 'subscribers.sync', 'uses' => 'SubscribersController@sync']);
    });
    // middleware who can manage posts
    Route::group(['middleware' => ['permission:manage-posts']], function () {
        //posts
        Route::resource('posts', 'PostsController', ['except' => ['show']]);
        Route::get('posts/search', ['as' => 'posts.search.admin', 'uses' => 'PostsController@search']);
        Route::get('posts/draft', ['as' => 'posts.draft', 'uses' => 'PostsController@draft']);
        Route::get('posts/pending', ['as' => 'posts.pending', 'uses' => 'PostsController@pending']);
        Route::get('posts/trash', ['as' => 'posts.trash', 'uses' => 'PostsController@trash']);
        Route::get('posts/trash/empty', ['as' => 'posts.trash.empty', 'uses' => 'PostsController@emptyTrash']);
        Route::get('posts/trash/{id}/restore', ['as' => 'posts.trash.restore', 'uses' => 'PostsController@restoreTrash']);
        Route::delete('posts/trash/{id}/delete', ['as' => 'posts.trash.delete', 'uses' => 'PostsController@deleteTrash']);
        Route::get('posts/check', ['as' => 'posts.check', 'uses' => 'PostsController@checkAllPosts']);
        //categories
        Route::resource('categories', 'CategoriesController', ['except' => ['show']]);
        //tags
        Route::resource('tags', 'TagsController', ['except' => ['show']]);
        Route::get('tags/lists', ['as' => 'tags.lists', 'uses' => 'TagsController@tagslist']);
        Route::resource('comments', 'CommentsController', ['only' => ['index', 'show', 'destroy']]);
        Route::get('comments/suspend/{id}', ['uses' => 'CommentsController@approveComment', 'as' => 'comments.approve']);
        Route::get('comments/active/{id}', ['uses' => 'CommentsController@suspendComment', 'as' => 'comments.suspend']);

    });
    // middleware who can manage menus
    Route::group(['middleware' => ['permission:manage-menus']], function () {
        //menus
        Route::get('menus', ['as' => 'menus.index', 'uses' => 'MenusController@index']);
        Route::get('menus/edit', ['as' => 'menus.edit', 'uses' => 'MenusController@edit']);
        Route::post('menus/store', ['as' => 'menus.store', 'uses' => 'MenusController@store']);
    });
    // middleware who can manage ads
    Route::group(['middleware' => ['permission:manage-ads']], function () {
        //ads controller
        Route::resource('ads', 'AdsController', ['except' => 'show']);
        Route::get('ads/upcoming', ['uses' => 'AdsController@upcoming', 'as' => 'ads.upcoming']);
        Route::get('ads/expired', ['uses' => 'AdsController@expired', 'as' => 'ads.expired']);
    });
    // middleware who can manage pages
    Route::group(['middleware' => ['permission:manage-pages']], function () {
        //pages
        Route::resource('pages', 'PagesController', ['except' => ['show']]);
        Route::post('pages/homepage', ['as' => 'pages.homepage.store', 'uses' => 'PagesController@storeHomepage']);
        Route::get('pages/section', ['as' => 'pages.section', 'uses' => 'PagesController@pageSections']);
    });

    // middleware who can manage widgets
    Route::group(['middleware' => ['permission:manage-widgets']], function () {
        //widgets
        Route::get('widgets', ['as' => 'widgets.index', 'uses' => 'WidgetsController@index']);
        Route::get('widgets/edit', ['as' => 'widgets.edit', 'uses' => 'WidgetsController@edit']);
        Route::post('widgets/store', ['as' => 'widgets.store', 'uses' => 'WidgetsController@store']);
    });
    Route::get('posts/info', ['as' => 'posts.info', 'uses' => 'PostsController@info']);
});

// Frontend Routes


Route::group(['namespace' => 'Frontend', 'middleware' => 'installed'], function () {
    Route::get('/', ['as' => 'home.index', 'uses' => 'HomeController@index']);
    Route::get('/posts/search', ['uses' => 'PostsController@search', 'as' => 'posts.search']);

app/Http/Controllers/Backend/AdsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Adspace;
use App\Http\Requests\Backend\AdRequest;
use App\Http\Controllers\Controller;
use App\Ad;

class AdsController extends Controller
{
    protected $ad;
    protected $adspace;

    public function __construct(Ad $ad, Adspace $adspace){
        $this->ad=$ad;
        $this->adspace=$adspace;
    }

    // Running Ads
    public function index(){
        $advertisements= $this->ad->runningAds()->orderBy('end_date')->paginate(20);
        return view('backend.ads.index',compact('advertisements'));
    }

    // Create Add View
    public function create(){
        $adspaces = $this->adspace->get();
        return view('backend.ads.create', compact('adspaces'));
    }

    //Store function
    public function store(AdRequest $request){
        $advertisement = $this->ad->create($request->all());
        if ($request->has('adspace_id')) {
            $advertisement->adspaces()->sync($request->input('adspace_id'));
        }
        if($request->input('submit') == 'save_continue'){
            return redirect()->route('ads.edit',$advertisement->id);
        }
        return redirect()->route('ads.index')->with('success','Ad Created Successfully');
    }

    //edit page
    public function edit($id){
        $advertisement = $this->ad->findorFail($id);
        $adspaces = $this->adspace->get();
        return view('backend.ads.edit',compact('advertisement','adspaces'));

    }

    //update function
    public function update(AdRequest $request,$id){
        $advertisement = $this->ad->findorFail($id);
        $advertisement->update($request->all());
        if ($request->has('adspace_id')) {
            $advertisement->adspaces()->sync($request->input('adspace_id'));
        }else{
            $advertisement->adspaces()->detach();
        }
        if($request->input('submit') == 'save_continue'){
            return redirect()->route('ads.edit',$advertisement->id);
        }
        return redirect()->route('ads.index')->with('success','Ad Updated Successfully');

    }

    //delte function
    public function destroy($id){
        $advertisement = $this->ad->findorFail($id);
        $advertisement->delete();
        return redirect()->back();
    }

    //upcoming ads
    public function upcoming(){
        $advertisements = $this->ad->upcomingAds()->orderBy('start_date')->paginate();
        return view('backend.ads.upcoming',compact('advertisements'));
    }

    //expired ads
    public function expired(){
        $advertisements=$this->ad->expiredAds()->orderBy('end_date')->paginate();
        return view('backend.ads.expired',compact('advertisements'));
    }
}

app/Http/Controllers/Backend/AdspacesController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Adspace;

class AdSpacesController extends Controller
{
    protected $adspace;

    public function __construct(Adspace $adspace){
        $this->adspace = $adspace;
    }

    //listing all adspaces
    public function index(){
        $adspaces=$this->adspace->orderBy('created_at')->paginate(20);
        return view('backend.adspaces.index',compact('adspaces'));
    }

    //storing adspaces
    public function store(Request $request){
        $this->validate($request,[
            'name' => 'required|string|max:255',
        ]);
        try{
            $this->adspace->create($request->only('slug', 'name', 'description'));
        }catch (\Exception $exception){
            dd($exception);
        }
        return redirect()->route('adspaces.index')->with('success','Ad Space Successfully updated!');
    }

    //delete fcuntion for adspaces
    public function destroy($id){
        try{
            $adspace=$this->adspace->findorFail($id);
            $adspace->delete();
        }catch (\Exception $exception){
            dd($exception);
        }
        return redirect()->back()->with('success','Ad Space Successfully Deleted!');
    }
    //edit page for adspaces
    public function edit($id){
        $adspace=$this->adspace->findOrFail($id);
        return view('backend.adspaces.edit',compact('adspace'));
    }

    //updating adspaces
    public function update(Request $request,$id){
        $this->validate($request,[
            'name' => 'required|string|max:255',
        ]);
        try{
            $adspace = $this->adspace->findOrFail($id);
            $adspace->update($request->only('name', 'description'));
        }catch (\Exception $exception){
            dd($exception);
        }
        return redirect()->route('adspaces.index')->with('success','Ad Space Successfully updated!');
    } 
}

app/Http/Controllers/Backend/CategoriesController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Str;
use App\Category;

class CategoriesController extends Controller
{
    protected $category;

    public function __construct(Category $category){
        $this->category = $category;
    }

    public function index(){
        $categories = $this->category->whereNull('parent_id')->with('children')->paginate();
        $allCategories = $this->category->pluck('name','id')->all();
    	return view('backend.categories.index',compact('categories','allCategories'));
    }

    //storing the newly created category
    public function store(Request $request){
    	$this->validate($request,[
    		'name'=>'required',
            'slug'=>'required|unique:categories'
        ]);
    	$input = $request->all();
        $input['parent_id'] = empty($input['parent_id']) ? NULL : $input['parent_id'];
        $this->category->create($input);
        return redirect()->back()->with('success','Category added successfully!');
    }

    
    //delete funtion
    public function destroy($id){
    	$category=$this->category->findorFail($id);
    	$category->delete();
    	return redirect()->back()->with('success','Category deleted successfully!');
    }

    public function edit($id){
    	$category=$this->category->find($id);
        $allCategories = $this->category->whereNull('parent_id')->where('id', '<>', $category->id)->pluck('name','id')->all();
        return view('backend.categories.edit',compact('category','allCategories'));
    }

    public function update(Request $request,$id){
    	$this->validate($request,[
    		'name'=>'required',
            'slug'=>'required'
    		]);
 		$category=$this->category->find($id);
        $parent_id = empty($request->input('parent_id')) ? NULL : $request->input('parent_id');
 		$category->update([
 			'name'=>$request->name,
 			'description'=>$request->description,
            'slug'=>$request->slug,
            'parent_id'=>$parent_id,
        ]);
 		return redirect()->route('categories.index')->with('success','Category updated successfully!');
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Category;
use App\Post;
use App\User;

class DashboardController extends Controller
{

    public function __construct(Category $category, Post $post, User $user){
    	$this->category=$category;
    	$this->post=$post;
    	$this->user=$user;
    }

    public function index(){
        $recentPosts= $this->post->published()->latest('publish_on')->take(5)->get();
        $popularPosts= $this->post->published()->orderBy('view_count', 'DESC')->take(5)->get();
        $users = $this->user->latest('created_at')->take(5)->get();
        return view('backend.dashboard', compact('recentPosts','popularPosts', 'users'));
    }
}

resources/views/backend/medias/_create.blade.php
{!! Form::open(['url' => route('media.store'), 'method'=>'post', 'class' => 'dropzone js-dropzone', 'files'=>true, 'id'=>'media-upload', 'data-modal'=>$modal]) !!}
{{Form::hidden('user_id', Auth::user()->id)}}
<div class="dz-message">
    <i class="fa fa-plus"></i>
    {{ __('site.media.drop_files') }}<br />
    <span class="note needsclick">{{ __('site.media.upload_info') }}<br /></span>
</div>
<div class="fallback">
    <input name="file" type="file" multiple />
</div>
{!! Form::close() !!}
<div class="text-right d-inline-block">
    <span class="text-info-active">
       {{ __('site.media.max_file_size') }} {{ ini_get('post_max_size') }}
    </span>
</div>

resources/views/backend/medias/_create_list.blade.php
@if($medias)
    @foreach($medias as $media)
    <div class="media-item">
        <div class="media-thumb">
          <img class="pinkynail" src="{{ $media->preview_url }}" alt="">
        </div>
        <div class="filename">
          <span>{{ $media->original_name }}</span>
        </div>
        <a href="javascript:void(0);" data-edit-url="{{ route('media.edit', $media->id) }}" class="edit-attachment" target="_blank"> {{ __('site.edit') }}</a>
    </div>
    @endforeach
@endif

resources/views/backend/medias/_index_list.blade.php
@if($medias)
    @foreach($medias as $media)
        <li class="attachment save-ready" data-edit-url="{{ route('media.edit', $media->id) }}" data-show-url="{{ route('media.show', $media->id) }}">
            <div class="attachment-preview landscape">
                <div class="thumbnail">
                    <div class="centered">
                        <img src="{{ $media->preview_url }}" alt="{{ $media->title }}">
                    </div>
                  <div class="filename">
                    <div>{{ $media->original_name }}</div>
                  </div>
                </div>
            </div>
        </li>
    @endforeach
@endif

resources/views/backend/medias/_modal-edit-partial.blade.php
<div class="row">
    <div class="col-md-6">
        <div class="attachment-details save-ready">
            <div class="attachment-media-view landscape">
                <div class="thumbnail thumbnail-image">
                    @if($media->type == 'image')
                    <img class="details-image" src="{{ url($media->media_url) }}" alt="">
                        @else
                        <img class="details-image" src="{{ $media->preview_url }}" alt="">
                        @endif
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="attachment-info">
            <div class="details">
                <div class="filename"><strong>{{ __('site.media.file_name') }}:</strong> {{ $media->filename }}</div>
                <div class="filename"><strong>{{ __('site.media.url') }}:</strong> {{ url($media->media_url) }}</div>
                <div class="filename"><strong>{{ __('site.media.file_type') }}:</strong> {{ $media->mime }}</div>
                <div class="uploaded"><strong>{{ __('site.media.uploaded_at') }}:</strong> {{ $media->created_at->format('l, d M Y') }}</div>
                <div class="file-size"><strong>{{ __('site.media.file_size') }}:</strong> {{ bytesToHuman(\Storage::size($media->upload_directory. '/'.$media->filename)) }}</div>
                <div class="compat-meta">
                </div>
            </div>
            <div class="settings">
                {!! Form::open(['url' => route('media.update', $media->id), 'method'=>'PATCH','role'=>'form','id'=>'attachment-edit']) !!}
                <div class="form-body">
                    <div class="form-group row">
                        {!!  Html::decode(Form::label('url',  __('site.media.url'), ['class' => 'col-lg-3 col-form-label']))  !!}
                        <div class="col-lg-9">
                            {!! Form::text('url',url($media->media_url) ,['class'=>'form-control','placeholder'=> __('site.media.url') ,'readonly']) !!}
                        </div>
                    </div>
                    <div class="form-group row">
                        {!!  Html::decode(Form::label('original_name',  __('site.title'), ['class' => 'col-lg-3 col-form-label']))  !!}
                        <div class="col-lg-9">
                            {!! Form::text('original_name',$media->original_name,['class'=>'form-control','placeholder'=> __('site.title')]) !!}
                        </div>
                    </div>
                    <div class="form-group row">
                        {!!  Html::decode(Form::label('caption',  __('site.media.caption'), ['class' => 'col-lg-3 col-form-label']))  !!}
                        <div class="col-lg-9">
                            {!! Form::textarea('caption',$media->caption,['size'=>'30x3', 'class'=>'form-control']) !!}
                        </div>
                    </div>
                    <div class="form-group row">
                        {!!  Html::decode(Form::label('original_name',  __('site.description'), ['class' => 'col-lg-3 col-form-label']))  !!}
                        <div class="col-lg-9">
                            {!! Form::textarea('description',$media->description,['size'=>'30x3', 'class'=>'form-control']) !!}
                        </div>
                    </div>
                    <input value="{{  __('site.save') }}" class="btn btn-md btn-outline-success" type="submit" id="attachment-save">
                    <span class="settings-save-status text-success" style="display:none">
                        <i class="fa fa-check-circle-o"></i>
                        <span class="saved">{{  __('site.media.saved') }}</span>
                    </span>
                </div>
                {!! Form::close() !!}
            </div>
            <div class="action text-right">
                {!! Form::open(array('route' => ['media.destroy',$media->id],  'method' => 'DELETE', 'role' => 'form',  'required' => 'required','id'=>'attachment-delete')) !!}
                    {!! Form::button('<i class="fa fa-trash"></i> '. __('site.delete'), array('class' => 'btn btn-sm btn-outline-danger','type' => 'submit')) !!}
                {!! Form::close()!!}
            </div>
        </div>
    </div>
</div>

resources/views/backend/medias/_modal-edit.blade.php
<!-- Large Modal -->
<div class="modal" id="edit-attachment-frame" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content ">
            <div class="modal-header">
              <h5 class="modal-title">{{ __('site.media.media_detail') }}</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true" class="fa fa-times-circle-o"></span>
              </button>
            </div>
          <div class="modal-body">
            <div id="media-frame-content" class="block">
            </div>
          </div>
        </div>
    </div>
</div>
<!-- END Large Modal -->

resources/views/backend/medias/_modal-show-partial.blade.php
<div class="block-content attachment-info">
    <div class="attachment-media-view landscape mb-20">
        <div id="media-selector" class="thumbnail thumbnail-image">
            <img class="details-image"  data-id="{{ $media->id }}" data-original-url="{{$media->media_url}}" src="{{ $media->preview_url }}" alt="{{ $media->caption }}">
        </div>
    </div>
    <div class="details">
        <div class="filename"><strong>{{ __('site.media.file_name') }}:</strong> {{ $media->filename }}</div>
        <div class="filename"><strong>{{ __('site.media.url') }}:</strong> {{ url($media->media_url) }}</div>
        <div class="filename"><strong>{{ __('site.media.file_type') }}:</strong> {{ $media->mime }}</div>
        <div class="uploaded"><strong>{{ __('site.media.uploaded_at') }}:</strong> {{ $media->created_at->format('l, d M Y') }}</div>
        <div class="file-size"><strong>{{ __('site.media.file_size') }}:</strong> {{ bytesToHuman(\Storage::size($media->upload_directory. '/'.$media->filename)) }}</div>
        @if($media->type == 'image')
            <div class="dimensions"><strong>{{ __('site.media.dimensions') }}:</strong> {{ imageDimention(\Storage::path($media->upload_directory.'/'.$media->filename), true) }}</div>
        @endif
        <div class="compat-meta">
        </div>
    </div>
    <div class="text-center mb-20">
        @if($media->type == 'image')
        <button id="set-image" type="button" class="btn btn-outline-primary mt-20">{{ __('site.media.select_media') }}</button>
        @endif
        <a id="insert-image" class="btn btn-outline-primary mt-20" href="javascript:insertCKeditor('{{ $media->media_url }}', '{{ $media->caption }}')">{{ __('site.media.insert_media') }}</a>
    </div>
</div>

resources/views/backend/medias/create.blade.php
@extends('backend.layout')
@section('title') {{ __('site.media.media_manager') }}  @endsection
@push('styles')

@endpush
@section('content')
  <div class="page-subheader mb-3">
    <div class="container-fluid">
      <div class="row align-items-center">
        <div class="col-md-7">
          <div class="list">
            <i class="fa fa-file-picture-o rounded-circle fs20 text-muted text-primary d-inline-block v-m"></i>
            <span class="d-inline-block title-lg ml-3 v-m">{{ __('site.media.media_manager') }} - {{ __('site.media.upload_media') }}</span>
          </div>
        </div>
        <div class="col-md-5">
          <div class="float-right">
            <a class="btn btn-outline-primary btn-sm" href="{{ route('media.index') }}"><i class="fa fa-list"></i> {{ __('site.media.media_list') }}</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="page-content d-flex flex">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12 mb-30">
          <div id="media-create" class="mb-20">
            @include('backend.medias._create', ['modal'=>'false'])
            <div id="info-load" style="display:none">{{ __('site.media.uploading') }}</div>
          </div>
          <div id="media-manager">

          </div>
        </div>
      </div>
    </div>
  </div>

@endsection
@push('modal')
    @include('backend.medias._modal-edit')
@endpush
@push('scripts')

@endpush

resources/views/backend/medias/index.blade.php
@extends('backend.layout')
@section('title') {{ __('site.media.media_manager') }}  @endsection
@push('styles')

@endpush
@section('content')
    <div class="page-subheader mb-3">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-md-4">
                    <div class="list">
                        <i class="fa fa-file-picture-o rounded-circle fs20 text-muted text-primary d-inline-block v-m"></i>
                        <span class="d-inline-block title-lg ml-3 v-m">{{ __('site.media.media_manager') }} </span>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="media-search float-right">
                        {!! Form::open(['route'=>'media.lists', 'method' => 'POST', 'role' => 'form' ,'class'=>'form-inline d-inline media-search-form']) !!}
                        {{ Form::select('type',[null => __('site.media.select_media_type'),'video'=>__('site.videos'),'image'=>__('site.images'),'audio'=>__('site.audios'), 'document'=>__('site.documents')],'',['class'=>'select2 form-control mb-2 mr-sm-2 mb-sm-0']) }}
                        {{ Form::text('s', old('s'), ['class'=>'form-control mb-2 mr-sm-2 mb-sm-0', 'placeholder'=> __('site.search')]) }}
                        {!! Form::close() !!}
                        <a class="btn btn-outline-primary btn-sm" href="{{ route('media.create') }}"><i class="fa fa-plus"></i> {{ __('site.media.add_new_media') }}</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="page-content">
        <div class="media-scroll">
            <ul id="media-list-modal" class="attachments" data-toggle="slimscroll" data-color="#42a5f5" data-opacity="1"
                data-always-visible="true" data-height="600px">
                @include('backend.medias._index_list')
            </ul>
        </div>
        @if($medias->lastPage() > 1)
            <div class="row mt-20 mb-20 media-load-footer text-center">
                <div class="col-md-12">
                    <a href="javascript:void(0);" id="load-more" class="btn btn-light loadmore-images">{{ __('site.media.load_more_media') }}</a>
                </div>
            </div>
        @endif
    </div>
@endsection
@push('modal')
    @include('backend.medias._modal-edit')
@endpush
@push('scripts')
    <script>
        $(".generate-thumbnail").click(function(e){
            e.preventDefault();
            var showcase = $(this);
            showcase.find('span').html("Generating...")
            $.ajax({
                type: 'GET',
                url: $(this).attr('href'),
                success: function(response){
                    showcase.find('span').html("<i class=\"fa fa-recycle\"></i> Regenerate Thumbnails");
                    uiHelperAlert('Success', response.data, 'success');
                }
            });
        });
    </script>
@endpush